### ISSUE TITLE
[1.16.4-4.0.3] server crash

### ISSUE THREAD

**Issue by Daejangnamu** [pau101/Fairy-Lights#103]
Description: Exception in server tick loop

java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_271] {}
	at me.paulf.fairylights.server.ServerEventHandler.onWorldTick(ServerEventHandler.java:179) ~[fairylights:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_162_ServerEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

[crash-2020-12-24_19.52.01-server.txt](https://github.com/pau101/Fairy-Lights/files/5739342/crash-2020-12-24_19.52.01-server.txt)

**Comment by 1q3** [comment]
same here on 1.16.3. started happening after moving the server from linux to windows
[crash-2020-12-24_03.17.26-server.txt](https://github.com/pau101/Fairy-Lights/files/5740570/crash-2020-12-24_03.17.26-server.txt)

**Comment by pau101** [comment]
Thanks for reporting! A new release will be out soon.

**Comment by pau101** [comment]
[Fairy Lights 4.0.4](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3148608) is now out.
