### ISSUE TITLE
IllegalStateException | 1.16.5

### ISSUE THREAD

**Issue by Kroko1337** [pau101/Fairy-Lights#121]
[15:01:04] [Render thread/FATAL]: Error mapping recipe fairylights:triangle_pennant. Failed to get ingredients due to the recipe not properly deserializing and handling tags. Please report this to fairylights.
java.lang.IllegalStateException: Tag forge:string used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?]
	at net.minecraft.tags.TagRegistry$NamedTag.func_230236_b_(TagRegistry.java:146) ~[?:?]
	at me.paulf.fairylights.util.crafting.ingredient.LazyTagIngredient.func_193365_a(LazyTagIngredient.java:26) ~[?:?]
	at me.paulf.fairylights.util.crafting.ingredient.GenericIngredient.getMatchingSubtypes(GenericIngredient.java:46) ~[?:?]
	at me.paulf.fairylights.util.crafting.ingredient.BasicRegularIngredient.getInputs(BasicRegularIngredient.java:25) ~[?:?]
	at me.paulf.fairylights.util.crafting.GenericRecipe.getDisplayIngredients(GenericRecipe.java:96) ~[?:?]
	at me.paulf.fairylights.util.crafting.GenericRecipe.func_192400_c(GenericRecipe.java:152) ~[?:?]
	at moze_intel.projecte.emc.mappers.recipe.BaseRecipeTypeMapper.getIngredients(BaseRecipeTypeMapper.java:209) ~[?:PE1.0.1B]
	at moze_intel.projecte.emc.mappers.recipe.BaseRecipeTypeMapper.getIngredientsChecked(BaseRecipeTypeMapper.java:194) [?:PE1.0.1B]
	at moze_intel.projecte.emc.mappers.recipe.BaseRecipeTypeMapper.handleRecipe(BaseRecipeTypeMapper.java:42) [?:PE1.0.1B]
	at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:72) [?:PE1.0.1B]
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:106) [?:PE1.0.1B]
	at moze_intel.projecte.emc.EMCReloadListener.func_195410_a(EMCReloadListener.java:30) [?:PE1.0.1B]
	at net.minecraft.resources.IResourceManagerReloadListener.func_232635_a_(IResourceManagerReloadListener.java:18) [?:?]
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$34892/464097674.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$35488/1728079487.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:167) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) [?:?]
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen$$Lambda$43666/828167924.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$43067/541840947.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$43066/495992491.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:111) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$34870/1589607419.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.24.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/1625817721.call(Unknown Source) [forge-1.16.5-36.1.24.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**Comment by pau101** [comment]
Looks like EMC is forcing its own semantics onto recipes. Nothing I can do about this incompatibility unfortunately.
