### ISSUE TITLE
Console Spam: World constructed without a WorldInfo! This will likely ca use problems. Subsituting dummy info.

### ISSUE THREAD

**Issue by TomberWolf** [pau101/Fairy-Lights#23]
The latest update triggers Sponge and spams the following issue endless in the server console:

```
[02:41:28] [Server thread/WARN] [Sponge]: World constructed without a WorldInfo! This will likely ca
use problems. Subsituting dummy info.
java.lang.RuntimeException: Stack trace:
        at net.minecraft.world.World.handler$onConstructed$zjn000(World.java:4773) [aid.class:?]
        at net.minecraft.world.World.<init>(World.java:133) [aid.class:?]
        at com.pau101.fairylights.server.item.ItemConnection$IsolatedBlock.<init>(ItemConnection.jav
a:176) [ItemConnection$IsolatedBlock.class:?]
        at com.pau101.fairylights.server.item.ItemConnection.isFence(ItemConnection.java:160) [ItemC
onnection.class:?]
        at com.pau101.fairylights.server.world.ServerWorldEventListener.func_184376_a(ServerWorldEve
ntListener.java:14) [ServerWorldEventListener.class:?]
        at net.minecraft.world.World.func_184138_a(World.java:415) [aid.class:?]
        at org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:511)
 [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2241]
        at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2665) [ls.class:?]
        at atomicstryker.ruins.common.RuinRuleAir.doBlock(RuinRuleAir.java:25) [RuinRuleAir.class:?]

        at atomicstryker.ruins.common.RuinTemplate.doBuildNested(RuinTemplate.java:412) [RuinTemplat
e.class:?]
        at atomicstryker.ruins.common.RuinTemplate.doBuild(RuinTemplate.java:313) [RuinTemplate.clas
s:?]
        at atomicstryker.ruins.common.RuinGenerator.createBuilding(RuinGenerator.java:274) [RuinGene
rator.class:?]
        at atomicstryker.ruins.common.RuinGenerator.generateNormal(RuinGenerator.java:197) [RuinGene
rator.class:?]
        at atomicstryker.ruins.common.RuinsMod.generateSurface(RuinsMod.java:221) [RuinsMod.class:?]

        at atomicstryker.ruins.common.RuinsMod.access$400(RuinsMod.java:43) [RuinsMod.class:?]
        at atomicstryker.ruins.common.RuinsMod$RuinsWorldGenerator.generate(RuinsMod.java:190) [Ruin
sMod$RuinsWorldGenerator.class:?]
        at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameR
egistry.java:665) [GameRegistry.class:?]
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[GameRegistry.class:?]
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001) [asv.class:?]
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983) [asv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) [
lr.class:?]
        at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3535) [Minecra
ftServer.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:8
17) [WorldManager.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:763) [WorldMa
nager.class:1.10.2-2254-5.2.0-BETA-2241]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3484) [MinecraftSe
rver.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld
.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class
:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Comment by pau101** [comment]
Can you try [this version](http://www.mediafire.com/file/dl554f3bf4nw3gz/fairylights-2.1.1-1.10.2.jar) to see if it fixes the issue?

**Comment by TomberWolf** [comment]
Seems to be fixed!
