### ISSUE TITLE
NullPointerException when ticking BlockEntityFastener

### ISSUE THREAD

**Issue by copygirl** [pau101/Fairy-Lights#74]
This happened on our server, causing the whole server to crash when anyone logs in near or comes closer to the affected block entity. We temporarily solved the issue by restarting the server after removing the mod, letting an affected player log in, then restarting the server again with the mod added back in. We have a backup of the world in the state that crashed, in case that helps.

The player likely causing the crash said they pushed a slab into a fairy light with a piston. (I have not tried to reproduce the issue myself.)

[Full crash log.](https://gist.github.com/copygirl/48a0d06989af28ead9e39fffffbd7d30)
```
java.lang.NullPointerException: Ticking block entity
	at com.pau101.fairylights.server.fastener.connection.type.Connection.update(Connection.java:290)
	at com.pau101.fairylights.server.fastener.FastenerDefault.update(FastenerDefault.java:77)
	at com.pau101.fairylights.server.block.entity.BlockEntityFastener.func_73660_a(BlockEntityFastener.java:69)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

### Versions
- **Minecraft:** `1.12.2`
- **Forge:** `14.23.5.2854`
- **Fairy Lights:** `2.1.10`

**Comment by pau101** [comment]
Thanks for reporting. An update will be out within the week along with the 1.15 port.

**Comment by pau101** [comment]
[Fairy Lights 2.1.11](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2995382) is now released to resolve this issue!
