### ISSUE TITLE
fairylights:black_string?

### ISSUE THREAD

**Issue by Scifidiva86** [pau101/Fairy-Lights#79]
Hello ran into this while trying to start up a new game:
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 7/19/20 1:49 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: fairylights:black_string
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:classloading}
	at me.paulf.fairylights.server.item.crafting.FLCraftingRecipes.makeHangingLights(FLCraftingRecipes.java:339) ~[?:?] {re:classloading}
	at me.paulf.fairylights.server.item.HangingLightsConnectionItem.func_150895_a(HangingLightsConnectionItem.java:57) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:596) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:434) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$424/1679352734.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
	at me.paulf.fairylights.server.item.crafting.FLCraftingRecipes.makeHangingLights(FLCraftingRecipes.java:339)
	at me.paulf.fairylights.server.item.HangingLightsConnectionItem.func_150895_a(HangingLightsConnectionItem.java:57)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:596)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:434)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$424/1679352734.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1133495384 bytes (1080 MB) / 2726821888 bytes (2600 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6912m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre28.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 LOAD_REGISTRIES}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 LOAD_REGISTRIES}
		pamhc2trees-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version LOAD_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 ERROR}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version LOAD_REGISTRIES}
		MagicalTorches-1.15.2-1.0.0.jar Magical Torches {magical_torches@1.0.0 LOAD_REGISTRIES}
		productivebees-1.15.2-0.1.11.jar Productive Bees {productivebees@1.15.2-0.1.11 LOAD_REGISTRIES}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 LOAD_REGISTRIES}
		storage_overhaul-1.15.2-1.0.5.jar Storage Overhaul {storage_overhaul@1.15.2-1.0.5 LOAD_REGISTRIES}
		fairylights-3.0.6-1.15.2.jar Fairy Lights {fairylights@3.0.6 LOAD_REGISTRIES}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 LOAD_REGISTRIES}
		Aquaculture-1.15.2-2.0.15.jar Aquaculture 2 {aquaculture@1.15.2-2.0.15 LOAD_REGISTRIES}
		BetterMineshaftsForge-1.15.2-1.0.2.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.0.2 LOAD_REGISTRIES}
		pamhc2foodcore-1.15.2-1.0.4.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version LOAD_REGISTRIES}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 LOAD_REGISTRIES}
		EnderMail-1.15.2-1.1.1.jar Ender Mail {endermail@1.15.2-1.1.1 LOAD_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 LOAD_REGISTRIES}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 LOAD_REGISTRIES}
		extragolems-10.2.1.jar Extra Golems {golems@10.2.1 LOAD_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 LOAD_REGISTRIES}
	Launched Version: forge-31.2.31
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon (TM) R9 390 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre28
	OptiFine Build: 20200619-233727
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: AMD Radeon (TM) R9 390 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by pau101** [comment]
Thanks for reporting!

Can you reproduce this crash with just fairy lights installed?

**Comment by Scifidiva86** [comment]
Did that got this:
[16:42:11] [main/INFO]: ModLauncher running: args [--username, Scifidiva86, --version, forge-31.2.31, --gameDir, C:\Users\\Twitch\Minecraft\Instances\Updated Forge (1), --assetsDir, C:\Users\\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, 19653a89d4774a3f951b7f4e8fd5f9fd, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.31, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[16:42:11] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[16:42:11] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[16:42:14] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-31.2.31, --gameDir, C:\Users\Kimberly\Twitch\Minecraft\Instances\Updated Forge (1), --assetsDir, C:\Users\Kimberly\Twitch\Minecraft\Install\assets, --uuid, 19653a89d4774a3f951b7f4e8fd5f9fd, --username, Scifidiva86, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[16:42:18] [Render thread/INFO]: Setting user: Scifidiva86
[16:42:30] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[16:42:32] [modloading-worker-1/INFO]: Forge mod loading, version 31.2.31, for MC 1.15.2 with MCP 20200515.085601
[16:42:32] [modloading-worker-1/INFO]: MinecraftForge v31.2.31 Initialized
[16:42:34] [Render thread/ERROR]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class biomesoplenty.init.ModBiomes registerBiomes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class biomesoplenty.init.ModItems registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class biomesoplenty.init.ModSounds registerSounds(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class biomesoplenty.init.ModBlocks registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class biomesoplenty.init.ModEntities registerEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NullPointerException
	at net.minecraft.item.MusicDiscItem.<init>(MusicDiscItem.java:37)
	at biomesoplenty.common.item.MusicDiscItemBOP.<init>(MusicDiscItemBOP.java:20)
	at biomesoplenty.init.ModItems.registerItems(ModItems.java:32)
	at net.minecraftforge.eventbus.ASMEventHandler_5_ModItems_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2216/1881309779.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2209/790851040.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2209/790851040.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126)
	at net.minecraftforge.fml.ModList$$Lambda$2329/728236551.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.ModList$$Lambda$2179/1078448857.dispatchEvent(Unknown Source)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206)
	at net.minecraftforge.fml.ModLoader$$Lambda$2356/271341439.accept(Unknown Source)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:995)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2063/333085360.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2064/747004588.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$404/1906947271.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

[16:42:34] [Render thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid biomesoplenty
java.lang.NullPointerException: null
	at net.minecraft.item.MusicDiscItem.<init>(MusicDiscItem.java:37) ~[?:?]
	at biomesoplenty.common.item.MusicDiscItemBOP.<init>(MusicDiscItemBOP.java:20) ~[?:?]
	at biomesoplenty.init.ModItems.registerItems(ModItems.java:32) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_5_ModItems_registerItems_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:31.2]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2216/1881309779.accept(Unknown Source) [?:31.2]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2209/790851040.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2209/790851040.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2329/728236551.accept(Unknown Source) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) [?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2179/1078448857.dispatchEvent(Unknown Source) [?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) [?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$2356/271341439.accept(Unknown Source) [?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:995) [?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2063/333085360.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2064/747004588.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$404/1906947271.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
[16:42:34] [Render thread/FATAL]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
[16:42:34] [Render thread/FATAL]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2064/747004588.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$404/1906947271.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
[16:42:36] [Render thread/INFO]: Narrator library for x64 successfully loaded
[16:42:36] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[16:42:36] [Server-Worker-3/WARN]: Configuration file C:\Users\Kimberly\Twitch\Minecraft\Instances\Updated Forge (1)\config\biomesoplenty\client.toml is not correct. Correcting
[16:42:36] [Server-Worker-3/WARN]: Incorrect key gui was corrected from null to SimpleCommentedConfig:{}
[16:42:36] [Server-Worker-3/WARN]: Incorrect key gui.use_world_type was corrected from null to true
[16:42:36] [Server-Worker-3/WARN]: Configuration file C:\Users\Kimberly\Twitch\Minecraft\Instances\Updated Forge (1)\config\biomesoplenty\generation.toml is not correct. Correcting
[16:42:36] [Server-Worker-3/WARN]: Incorrect key overworld was corrected from null to SimpleCommentedConfig:{}
[16:42:36] [Server-Worker-3/WARN]: Incorrect key overworld.biome_size was corrected from null to MEDIUM
[16:42:36] [Server-Worker-3/WARN]: Incorrect key overworld.river_size was corrected from null to MEDIUM
[16:42:36] [Server-Worker-3/WARN]: Incorrect key overworld.temperature_variation_scheme was corrected from null to MEDIUM_ZONES
[16:42:36] [Server-Worker-3/WARN]: Incorrect key overworld.rainfall_variation_scheme was corrected from null to MEDIUM_ZONES
[16:42:36] [Server-Worker-3/WARN]: Incorrect key overworld.enhance_vanilla_biomes was corrected from null to true
[16:42:36] [Server-Worker-3/WARN]: Configuration file C:\Users\Kimberly\Twitch\Minecraft\Instances\Updated Forge (1)\config\biomesoplenty\server.toml is not correct. Correcting
[16:42:36] [Server-Worker-3/WARN]: Incorrect key biomes was corrected from null to SimpleCommentedConfig:{}
[16:42:36] [Server-Worker-3/WARN]: Incorrect key biomes.use_world_type was corrected from null to true
[16:42:36] [Server-Worker-3/ERROR]: Skipping lifecycle event SETUP, 1 errors found.
[16:42:36] [Server-Worker-3/FATAL]: Failed to complete lifecycle event SETUP, 1 errors found
[16:42:36] [Server-Worker-3/FATAL]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2064/747004588.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2676/2093834526.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2064/747004588.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[16:43:04] [Server-Worker-2/ERROR]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[16:43:04] [Server-Worker-2/FATAL]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[16:43:04] [Server-Worker-2/FATAL]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2064/747004588.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2678/294817977.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[16:43:04] [Render thread/INFO]: OpenAL initialized.
[16:43:04] [Render thread/INFO]: Sound engine started
[16:43:05] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[16:43:05] [Render thread/INFO]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[16:43:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16:43:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16:43:05] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[16:43:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[16:43:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:43:06] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[16:43:06] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[16:43:06] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
